name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "Hola Mundo!"
            echo "Bonjour le monde!"
      - name: Print goodbye
        run: echo "Bye!"        
